kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: composer
  commands:
  - cd backend && composer install

- name: frontend
  image: node
  commands:
  - cd frontend && npm install && npm run build

- name: build-docker-image
  image: plugins/docker
  settings:
    auto_tag: true
    dockerfile: docker/Dockerfile
    repo: https://registry.xrg.io/salvarez/xrg.es
    registry: https://registry.xrg.io
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
  #when:
  #  event:
  #  - tag

- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    username: Drone
