kind: pipeline
type: docker
name: default

steps:
- name: say-hello
  image: busybox
  commands:
  - echo hello-world

- name: backend
  image: composer
  commands:
  - cd backend && composer install

- name: frontend
  image: node
  commands:
  - cd frontend && npm install

- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    username: Drone
    message: >
      {{#success build.status}}
        {{build.event}}: build #{{build.number}} succeeded.
      {{else}}
        {{build.event}}: build #{{build.number}} failed.
      {{/success}}
      {{build.link}}
      {{datetime build.started}} - {{since build.started}}
