kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: composer:2.1.14
  commands:
  - cd backend && composer install

- name: frontend
  image: node:16.13.1
  commands:
  - cd frontend && npm install && npm run build

- name: build-docker-image
  image: plugins/docker
  settings:
    context: docker/
    dockerfile: Dockerfile
    auto_tag: true
    repo: https://registry.xrg.io/salvarez/xrg.es
    registry: https://registry.xrg.io
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
  #when:
  #  event:
  #  - tag
