kind: pipeline
type: docker
name: default

steps:
- name: say-hello
  image: busybox
  commands:
  - echo hello-world

- name: backend
  image: composer
  commands:
  - cd backend && composer install

- name: frontend
  image: node
  commands:
  - cd frontend && npm install