version: '3.8'

services:
  xrges-nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8086:80"
    volumes:
      - ../frontend/build:/var/www/frontend
      - ./zz-default-nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - xrges-php

  xrges-php:
    build: .
    restart: unless-stopped
    volumes:
      - ../backend:/var/www/backend

  xrges-redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - ../home/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

networks:
  default:
    name: xrges-network
