version: '3.8'

services:
  xrges-nginx:
    image: registry.xrg.io/xrges/nginx:latest
    restart: unless-stopped
    ports:
      - "8086:80"
    links:
      - xrges-php

  xrges-php:
    image: registry.xrg.io/xrges/php:latest
    restart: unless-stopped

  xrges-redis:
    image: registry.xrg.io/xrges/redis:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data

networks:
  default:
    name: xrges-network

volumes:
    redis_data:
